version: "3.8"
services:
  backend:
    image: "jdavault/spring-react-fullstack:31.1.2022.22.49.28"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev
